### ISSUE TITLE
When will RavenDB 4 be supported?

### ISSUE THREAD

**Issue by drikusvd** [ravendb/quartznet-RavenDB#13]
Since RavenDB 4 changed the way you connect to a document store the current version of Quartz.NET-RavenDB is not compatible with RavenDB 4. Are there any plans to support RavenDB 4?

**Comment by iftahbe** [comment]
Sorry, it's not planned in the near future.
You can submit a PR if you feel up to it :)

**Comment by lahma** [comment]
If I were to submit a PR, should there be a separate project (nuget package) for quartz3+raven4?

**Comment by lahma** [comment]
@iftahbe / @ayende other option is if you want to donate source to Quartz.NET I can make RavenDB 4 integration part of the code base and run smoke tests etc against it. This original work would stay here.

**Comment by ayende** [comment]
We would be very happy to donate the source for the RavenDB <--> Quartz.NET integration.

**Comment by lahma** [comment]
Great news! I'll work on integrating the tweaked source to Quartz.NET source tree attributing you as the original authors. So there will be a new NuGet package something like Quartz.JobStore.RavenDB4 or something similar which will be part of Quartz.NET 3.x release cycle.

**Comment by jabellard** [comment]
@lahma , @ayende : Any updates on  getting this package to work with Raven 4?

**Comment by ayende** [comment]
This is likely going to wait until someone would pick it up.
Would you be interested in doing so?

**Comment by lahma** [comment]
I have branch under work, that I started months ago but life got into the way. I'll try to check/rebase/ update and check the status. Generally I was planning to make bigger changes to store APIs to make things a bit more saner. So with changes it would be Quartz v4.

**Comment by jabellard** [comment]
@lahma  : Any updates on this?

**Comment by oiBio** [comment]
We are also looking for a solution. Anyone has something working for RavenDB 4/5?

**Comment by ayende** [comment]
We would love to help out anyone who wishes to update this.

**Comment by nefarius** [comment]
I've picked up working on Quartz.NET 3.3.x and RavenDB 5.x compatibility [in this fork](https://github.com/nefarius/quartznet-RavenDB/tree/nefarius/ravendb5). Got the provided example working, still a fair bit to do but it doesn't look too bad, the worst is done 😅

**Comment by nefarius** [comment]
There we go 🥳 

![image](https://user-images.githubusercontent.com/286631/129428347-01d05dce-2ec1-45f7-8dcf-5f91623ad8bd.png)

**Comment by nefarius** [comment]
I've put it in production today, confidence, yay 😆 

@ayende @lahma pardon the ping; how'd you like me to go forward? PR? Completely new NuGet? More tests? Something else? 😇

**Comment by ayende** [comment]
A PR would be great, I think

**Comment by nefarius** [comment]
Done in #14
