### ISSUE TITLE
Fixing NullReferenceExeption + Fixing how some queries are executed

### ISSUE THREAD

**Issue by mouradchama** [ravendb/quartznet-RavenDB#18]
Hello,

I have fixed some bugs discovered on the latest version.

1. We have a NullReferenceException when no Scheluer is present in the Database, It happens on the first execution.
2. Two queries are exeted synchronously ( with ToList method instead of ToListAsync method) on the asynchronous Session (IAsyncDocumentSession)

this is the pull request: [https://github.com/ravendb/quartznet-RavenDB/pull/17](url)

Regards,
Mourad

**Comment by ayende** [comment]
Thanks, merged.
