### ISSUE TITLE
Jobs don't always start at the right time

### ISSUE THREAD

**Issue by cadilhac** [ravendb/quartznet-RavenDB#22]
I recently noticed that when creating triggers with a StartNow() or StartAt() option, then, more often than not, the job is not started at the right time. For instance, I have a "send email" job configured to start in 2 seconds. Checking in the debugger, I see that it starts 25 seconds after the call.
Now, if I use Quartz in memory instead of  using a ravendb store, then jobs perfectly start at the right time.

Any idea about this mystery? @ayende ?

**Comment by ayende** [comment]
Maybe there is some delay in how often it checks for tasks? The refresh rate?

**Comment by cadilhac** [comment]
You mean quartz.net? Unsure, because sometimes a StartNow is done instantly, sometimes it waits far too many seconds...

**Comment by ayende** [comment]
Let's start from the basics. 
If you do this test with the traffic watch active, what do you observe?

**Comment by cadilhac** [comment]
Here is a screeshot of the traffic log. The first 8 rows appear when the job is created (this is a job that is set to start in 2 seconds). The next rows appear 25 seconds later.

![timing](https://user-images.githubusercontent.com/50608/190447544-457e478c-6a74-4d9c-9df3-94f23b0248e4.jpg)

The job is PUT at 11:34:48. The time in the next trigger query is set to 30 seconds later at 11:35:18. Why? I don't know.
Then at 11:35:13, i.e. 25 seconds later, it goes live again and the job is run.
Does it make sense to you?

**Comment by cadilhac** [comment]
I made further tests and something is beyond my understanding. In RavenJobStore.AcquireNextTriggers, there is:

```cs
var triggersQuery = await session
    .Query<Trigger>()
    .Where(t =>
        t.State == InternalTriggerState.Waiting &&
        t.NextFireTimeUtc <= (noLaterThan + timeWindow).UtcDateTime)
    .OrderBy(t => t.NextFireTimeTicks)
    .ThenByDescending(t => t.Priority)
    .ToListAsync(cancellationToken);
```

I noticed that it was returning empty even if there was a trigger with a NextFireTimeUtc lesser than the (noLaterThan + timeWindow).UtcDateTime.
So I added a test query like this:

```cs
var testQuery = (await session.Query<Trigger>().ToListAsync())
    .Where(t => (t.State == InternalTriggerState.Waiting) && (t.NextFireTimeUtc <= maxTime))
    .ToList();
```

This one returns correctly my trigger. So something bad happens with the comparison of dates on the ravendb server...

Many seconds later, when the method is fired again, then the dates comparison works and the trigger is returned, but late.

**Comment by cadilhac** [comment]
Something very interesting to note:

At first, when the trigger is saved in the database, NextFireTimeUtc is "2022-09-16T09:35:17.1950389-04:00". Note the time offset -4.
At this time the above query doesn't work and the trigger is saved with a new NextFireTimeUtc. But this time, it is actually saved as UTC: 2022-09-16T13:35:47.1950389+00:00, i.e. as UTC. Then next time, the query works.

Even better. If I put a breakpoint before the query is done for the first time, and I go into the db to manually modify the time from local to UTC (i.e. from -04:00 to +00:00), then the query works.

**Comment by cadilhac** [comment]
In your Trigger constructor, I added:

```cs
if (NextFireTimeUtc.HasValue && NextFireTimeUtc.Value.Offset.Ticks != 0)
    NextFireTimeUtc = NextFireTimeUtc.Value.UtcDateTime;
if (StartTimeUtc.Offset.Ticks != 0)
    StartTimeUtc = StartTimeUtc.UtcDateTime;
if (FinalFireTimeUtc.HasValue && FinalFireTimeUtc.Value.Offset.Ticks != 0)
    FinalFireTimeUtc = FinalFireTimeUtc.Value.UtcDateTime;
```

This is a workaround that fixes the issue. But this is only a workaround that does not answer both questions:

1. Why does the Quartz.net library initially gives you local times, then later gives you UTC times (in GetNextFireTimeUtc())?
2. Why the RavenDb server is not able to correctly compare 2 dates, one in local time and one in UTC?

That's it for today.

**Comment by cadilhac** [comment]
I think I get it. After the trigger is initially created and saved, the automatic index has not the time to update before the query is made. I found this out by adding an await Task.Delay(2000); before the query is made.
I tried to add some session.Advanced.WaitForIndexesAfterSaveChanges in various places and it mainly fixed the issue, but sometimes not so I guess I'm missing a detail here. Also why no WaitForIndexesAfterSaveChanges async version?
@ayende The ball is in your court now.

**Comment by cadilhac** [comment]
I think I get it. After the trigger is initially created and saved, the automatic index has not the time to update before the query is made. I found this out by adding an await Task.Delay(2000); before the query is made.
Therefore I added some session.Advanced.WaitForIndexesAfterSaveChanges calls in each StoreJob/Trigger method and it fixed the issue.

**Comment by ayende** [comment]
Okay, that make sense, then. Thanks for figuring it out.
