### ISSUE TITLE
Nuget package

### ISSUE THREAD

**Issue by hg5fm** [ravendb/quartznet-RavenDB#7]
Hi,
I think there is a problem with the nuget package v1.0.4. It looks like the Quartz.Impl.RavenDB.dll doesn't contains the fix related to ApiKey. I've also checked with a decompiler and I couldn't find the ApiKey code in it. 
Could you please check it.
Thank you.

**Comment by iftahbe** [comment]
Sure

**Comment by iftahbe** [comment]
You're right, that's very weird.
Anyway... I updated the nuget package again and now it seems to work nicely.
