### ISSUE TITLE
Exception when creating a new trigger

### ISSUE THREAD

**Issue by alexeyzimarev** [ravendb/quartznet-RavenDB#9]
When new trigger is getting created, I get this exception:

> [13:54:05 ERR] quartzSchedulerThreadLoop: RuntimeException Unable to cast object
>  of type 'Quartz.Impl.RavenDB.Trigger' to type 'Quartz.Impl.RavenDB.Job'.
> System.InvalidCastException: Unable to cast object of type 'Quartz.Impl.RavenDB.
> Trigger' to type 'Quartz.Impl.RavenDB.Job'.
>    at Raven.Client.Document.DocumentSession.Load[T](String id) in c:\Builds\Rave
> nDB-Stable-3.0\Raven.Client.Lightweight\Document\DocumentSession.cs:line 263
>    at Quartz.Impl.RavenDB.RavenJobStore.AcquireNextTriggers(DateTimeOffset noLat
> erThan, Int32 maxCount, TimeSpan timeWindow)
>    at Quartz.Core.QuartzSchedulerThread.Run() in c:\Program Files (x86)\Jenkins\
> workspace\Quartz.NET\src\Quartz\Core\QuartzSchedulerThread.cs:line 253

**Comment by iftahbe** [comment]
Hi Alexey,
First of all, thanks for the feedback.
I am not getting this exception when [creating triggers in the demo](https://github.com/ravendb/quartznet-RavenDB/blob/master/src/Examples/RavenJobStoreDemo.cs).
Can you please explain what kind of trigger you're creating and how? Or even better, supply a short failing test?

**Comment by alexeyzimarev** [comment]
I will try to create a reproduction, I am on holidays now.
